'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/lib/supabase';
import {
  fetchAllReflections,
  fetchMonthlyReflectionCount,
  fetchUserSelections,
  generateReflections,
} from '@/lib/api';

import { Colors } from '@/constants/theme';
import { AppShell } from '@/components/AppShell';
import { Database } from '@/lib/database.types';

type Reflection = Database['public']['Tables']['reflections']['Row'];

const MONTHLY_LIMIT = 6;

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric',
  });
}

function nextMonthName() {
  const d = new Date();
  d.setMonth(d.getMonth() + 1);
  return d.toLocaleDateString('en-GB', { month: 'long' });
}

function toTexts(content: unknown): string[] {
  if (!Array.isArray(content)) return [];
  return content.filter((x): x is string => typeof x === 'string');
}

function PastReflectionGroup({ reflection }: { reflection: Reflection }) {
  const [expanded, setExpanded] = useState(false);
  const texts = toTexts(reflection.content);

  return (
    <div className="rounded-xl bg-white mb-2.5 overflow-hidden b-card">
      <button
        onClick={() => setExpanded((v) => !v)}
        className="w-full flex items-center justify-between px-4 py-3.5 min-h-[44px] hover:bg-gray-50 transition-colors text-left"
      >
        <span className="text-sm text-ink font-medium">{formatDate(reflection.generated_at)}</span>
        <span className="text-xs text-subtext">{expanded ? '▲' : '▼'}</span>
      </button>
      {expanded && (
        <div className="px-4 pb-4">
          <div className="flex flex-col gap-4">
            {texts.map((text, i) => (
              <p key={i} className="text-ink text-base leading-relaxed" style={{ lineHeight: '26px' }}>{text}</p>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

export default function ReflectionsPage() {
  const router = useRouter();
  const queryClient = useQueryClient();
  const [userId, setUserId] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [genError, setGenError] = useState('');
  const [confirmOpen, setConfirmOpen] = useState(false);
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    supabase.auth.getUser().then(({ data }) => {
      if (!data.user) { router.replace('/'); return; }
      setUserId(data.user.id);
    });
  }, [router]);

  const { data: allReflections = [], isLoading: reflLoading } = useQuery({
    queryKey: ['all-reflections', userId],
    queryFn: () => fetchAllReflections(userId!),
    enabled: !!userId,
  });

  const { data: monthlyCount = 0 } = useQuery({
    queryKey: ['monthly-reflection-count', userId],
    queryFn: () => fetchMonthlyReflectionCount(userId!),
    enabled: !!userId,
  });

  const { data: selectedIds = [], isLoading: selectionsLoading } = useQuery({
    queryKey: ['user-selections', userId],
    queryFn: () => fetchUserSelections(userId!),
    enabled: !!userId,
  });

  const isLoading = reflLoading || selectionsLoading;
  const hasThemes = selectedIds.length > 0;
  const atLimit = monthlyCount >= MONTHLY_LIMIT;
  const latest = allReflections[0] ?? null;
  const past = allReflections.slice(1);
  const latestTexts = latest ? toTexts(latest.content) : null;
  const remaining = MONTHLY_LIMIT - monthlyCount;

  async function handleGenerate() {
    if (!userId || generating || atLimit) return;
    setGenerating(true);
    setGenError('');
    try {
      await generateReflections(userId);
      await queryClient.invalidateQueries({ queryKey: ['all-reflections', userId] });
      await queryClient.invalidateQueries({ queryKey: ['monthly-reflection-count', userId] });
    } catch (err: unknown) {
      setGenError(err instanceof Error ? err.message : 'Something went wrong.');
    } finally {
      setGenerating(false);
    }
  }

  function confirmGenerate() {
    if (!userId || generating || atLimit) return;
    if (!latestTexts) { handleGenerate(); return; }
    setConfirmOpen(true);
  }

  useEffect(() => {
    if (!userId || isLoading || hasAutoGenerated.current) return;
    if (latest) return;
    if (!hasThemes || atLimit) return;
    hasAutoGenerated.current = true;
    handleGenerate();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId, isLoading, latest, hasThemes, atLimit]);

  if (isLoading || (generating && !latestTexts)) {
    return (
      <AppShell active="reflections">
        <div className="flex flex-col items-center justify-center min-h-[60vh] text-center gap-5">
          <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin" />
          <p className="font-georgia text-primary text-xl leading-relaxed max-w-sm">
            {generating ? "We're shaping something thoughtful for you…" : 'Loading your AI Reflection…'}
          </p>
        </div>
      </AppShell>
    );
  }

  if (!hasThemes) {
    return (
      <AppShell active="reflections">
        <div className="flex flex-col items-center justify-center min-h-[60vh] text-center">
          <h2 className="font-georgia text-primary text-2xl mb-3">Choose your themes first</h2>
          <p className="text-subtext text-base leading-relaxed mb-8 max-w-md">
            Head to ADOPT Themes to select your themes, then return here to generate your AI Reflection.
          </p>
          <Link
            href="/adopt"
            className="flex items-center justify-center h-12 px-8 rounded-xl bg-primary text-white text-sm font-semibold hover:opacity-90 transition-opacity"
          >
            Choose ADOPT Themes
          </Link>
        </div>
      </AppShell>
    );
  }

  return (
    <AppShell active="reflections">
      <div className="max-w-5xl mx-auto px-8 py-10">

        {/* Header */}
        <div className="flex justify-end mb-6">
          <button
            onClick={confirmGenerate}
            disabled={generating || atLimit}
            className="flex items-center justify-center h-11 px-7 rounded-xl text-sm font-semibold transition-opacity disabled:opacity-60 shrink-0"
            style={{ backgroundColor: atLimit ? Colors.subtext + '80' : Colors.primary, color: 'white' }}
          >
            {generating ? (
              <span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
            ) : (
              atLimit ? 'Monthly limit reached' : latestTexts ? 'Regenerate' : 'Generate'
            )}
          </button>
        </div>

        {/* Monthly usage */}
        <div
          className="rounded-xl px-4 py-3 mb-8 flex items-center justify-between"
          style={{ backgroundColor: atLimit ? Colors.error + '15' : Colors.accent + '20' }}
        >
          {atLimit ? (
            <p className="text-sm text-ink">
              You&apos;ve used all {MONTHLY_LIMIT} AI Reflections for this month. Resets in {nextMonthName()}.
            </p>
          ) : (
            <>
              <span className="text-sm text-ink">
                {monthlyCount} of {MONTHLY_LIMIT} AI Reflections used this month
              </span>
              <span className="text-sm text-subtext">{remaining} left</span>
            </>
          )}
        </div>

        {/* AI Reflection explanation */}
        <div className="rounded-2xl p-6 mb-8" style={{ backgroundColor: Colors.secondary + '25' }}>
          <h2 className="font-georgia text-primary text-xl mb-4">AI Reflection</h2>
          <div className="flex flex-col gap-3 text-sm text-ink leading-relaxed">
            <p>Your ADOPT choices are unique to you.</p>
            <p>
              Claude, an AI tool by Anthropic, uses your chosen themes to generate a personal reflection.
            </p>
            <p>
              This is not advice, diagnosis or instruction. It is a prompt to help you pause, notice
              patterns and think more deeply about your life, work and next steps.
            </p>
            <p className="font-medium text-primary">You are always the expert on your own life.</p>
            <p>
              Read it if it helps. Ignore it if it does not. You can refresh it up to six times each month.
            </p>
          </div>
        </div>

        {genError && (
          <p className="text-error text-sm mb-4">{genError}</p>
        )}

        {/* Latest reflection — single box */}
        {latestTexts ? (
          <div className="mb-10">
          <h1 className="font-georgia text-primary text-3xl leading-tight mb-1">What Claude noticed in your ADOPTs</h1>
          {latest && (
            <p className="text-subtext text-sm mb-4">Generated {formatDate(latest.generated_at)}</p>
          )}
          <div className="bg-white rounded-2xl p-6 border border-secondary/30 shadow-sm">
            <div className="flex flex-col gap-4">
              {latestTexts.map((text, i) => (
                <p key={i} className="text-ink text-base leading-relaxed" style={{ lineHeight: '26px' }}>{text}</p>
              ))}
            </div>
          </div>
          </div>
        ) : (
          <p className="text-subtext text-sm py-12 text-center">
            Your AI Reflection will appear here once generated
          </p>
        )}

        {/* Past generations */}
        {past.length > 0 && (
          <div className="mt-4">
            <p className="text-xs font-semibold text-subtext uppercase tracking-wider mb-4">
              Previous AI Reflections
            </p>
            <div className="flex flex-col gap-2">
              {past.map((r) => <PastReflectionGroup key={r.id} reflection={r} />)}
            </div>
          </div>
        )}
      </div>

      {/* Confirm dialog */}
      {confirmOpen && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 px-6">
          <div className="bg-background rounded-2xl p-6 w-full max-w-sm">
            <h3 className="font-georgia text-primary text-lg mb-2">Regenerate AI Reflection?</h3>
            <p className="text-sm text-ink leading-relaxed mb-6">
              This will create a new AI Reflection and use one of your monthly allowances.
              Your previous AI Reflections will still be available in history.
            </p>
            <div className="flex gap-3">
              <button
                onClick={() => setConfirmOpen(false)}
                className="flex-1 min-h-[44px] rounded-xl border-[1.5px] border-secondary text-ink text-sm hover:bg-secondary/20 transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={() => { setConfirmOpen(false); handleGenerate(); }}
                className="flex-1 min-h-[44px] rounded-xl bg-primary text-white text-sm font-semibold hover:opacity-90 transition-opacity"
              >
                Regenerate
              </button>
            </div>
          </div>
        </div>
      )}
    </AppShell>
  );
}
