'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/lib/supabase';
import {
  fetchAllReflections,
  fetchMonthlyReflectionCount,
  fetchUserSelections,
  generateReflections,
} from '@/lib/api';
import { ReflectionCard } from '@/components/ReflectionCard';
import { Colors } from '@/constants/theme';
import { AppShell } from '@/components/AppShell';
import { Database } from '@/lib/database.types';

type Reflection = Database['public']['Tables']['reflections']['Row'];

const MONTHLY_LIMIT = 6;

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric',
  });
}

function nextMonthName() {
  const d = new Date();
  d.setMonth(d.getMonth() + 1);
  return d.toLocaleDateString('en-GB', { month: 'long' });
}

function PastReflectionGroup({ reflection }: { reflection: Reflection }) {
  const [expanded, setExpanded] = useState(false);
  const texts = reflection.content as string[];

  return (
    <div className="rounded-xl border bg-white mb-2.5 overflow-hidden" style={{ borderColor: Colors.secondary + '60' }}>
      <button
        onClick={() => setExpanded((v) => !v)}
        className="w-full flex items-center justify-between px-4 py-3.5 min-h-[44px] hover:bg-gray-50 transition-colors text-left"
      >
        <span className="text-sm text-ink font-medium">{formatDate(reflection.generated_at)}</span>
        <span className="text-xs text-subtext">{expanded ? '▲' : '▼'}</span>
      </button>
      {expanded && (
        <div className="px-3 pb-3">
          {texts.map((text, i) => <ReflectionCard key={i} text={text} index={i} />)}
        </div>
      )}
    </div>
  );
}

export default function ReflectionsPage() {
  const router = useRouter();
  const queryClient = useQueryClient();
  const [userId, setUserId] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [genError, setGenError] = useState('');
  const [confirmOpen, setConfirmOpen] = useState(false);
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    supabase.auth.getUser().then(({ data }) => {
      if (!data.user) { router.replace('/'); return; }
      setUserId(data.user.id);
    });
  }, [router]);

  const { data: allReflections = [], isLoading: reflLoading } = useQuery({
    queryKey: ['all-reflections', userId],
    queryFn: () => fetchAllReflections(userId!),
    enabled: !!userId,
  });

  const { data: monthlyCount = 0 } = useQuery({
    queryKey: ['monthly-reflection-count', userId],
    queryFn: () => fetchMonthlyReflectionCount(userId!),
    enabled: !!userId,
  });

  const { data: selectedIds = [], isLoading: selectionsLoading } = useQuery({
    queryKey: ['user-selections', userId],
    queryFn: () => fetchUserSelections(userId!),
    enabled: !!userId,
  });

  const isLoading = reflLoading || selectionsLoading;
  const hasThemes = selectedIds.length > 0;
  const atLimit = monthlyCount >= MONTHLY_LIMIT;
  const latest = allReflections[0] ?? null;
  const past = allReflections.slice(1);
  const latestTexts = latest ? (latest.content as string[]) : null;
  const remaining = MONTHLY_LIMIT - monthlyCount;

  async function handleGenerate() {
    if (!userId || generating || atLimit) return;
    setGenerating(true);
    setGenError('');
    try {
      await generateReflections(userId);
      await queryClient.invalidateQueries({ queryKey: ['all-reflections', userId] });
      await queryClient.invalidateQueries({ queryKey: ['monthly-reflection-count', userId] });
    } catch (err: unknown) {
      setGenError(err instanceof Error ? err.message : 'Something went wrong.');
    } finally {
      setGenerating(false);
    }
  }

  function confirmGenerate() {
    if (!userId || generating || atLimit) return;
    if (!latestTexts) { handleGenerate(); return; }
    setConfirmOpen(true);
  }

  useEffect(() => {
    if (!userId || isLoading || hasAutoGenerated.current) return;
    if (latest) return;
    if (!hasThemes || atLimit) return;
    hasAutoGenerated.current = true;
    handleGenerate();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId, isLoading, latest, hasThemes, atLimit]);

  if (isLoading || (generating && !latestTexts)) {
    return (
      <AppShell active="reflections">
        <div className="flex flex-col items-center justify-center min-h-[60vh] px-8 text-center gap-5">
          <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin" />
          <p className="font-georgia text-primary text-lg leading-relaxed">
            {generating ? "We're shaping something thoughtful for you…" : 'Loading your reflections…'}
          </p>
        </div>
      </AppShell>
    );
  }

  if (!hasThemes) {
    return (
      <AppShell active="reflections">
        <div className="flex flex-col items-center justify-center min-h-[60vh] px-8 text-center">
          <h2 className="font-georgia text-primary text-[22px] mb-3">Choose your themes first</h2>
          <p className="text-subtext text-sm leading-relaxed mb-8">
            Head to the Themes tab to select your ADOPT themes, then return here to generate your
            reflections.
          </p>
          <Link
            href="/adopt"
            className="flex items-center justify-center min-h-[50px] px-7 rounded-xl bg-primary text-white text-sm font-semibold hover:opacity-90 transition-opacity"
          >
            Choose Themes
          </Link>
        </div>
      </AppShell>
    );
  }

  return (
    <AppShell active="reflections">
      <div className="px-5 pb-36 pt-3">

        {/* Header */}
        <div className="mb-5">
          <h1 className="font-georgia text-primary text-[28px] leading-[36px]">Points of Reflection</h1>
          {latest && (
            <p className="text-subtext text-xs mt-1">Generated {formatDate(latest.generated_at)}</p>
          )}
        </div>

        {/* Monthly usage */}
        <div
          className="rounded-lg px-3.5 py-2.5 mb-6 flex items-center justify-between"
          style={{ backgroundColor: atLimit ? Colors.error + '15' : Colors.accent + '25' }}
        >
          {atLimit ? (
            <p className="text-sm text-ink leading-5">
              You&apos;ve used all {MONTHLY_LIMIT} reflections for this month. Resets in {nextMonthName()}.
            </p>
          ) : (
            <>
              <span className="text-sm text-ink">
                {monthlyCount} of {MONTHLY_LIMIT} reflections used this month
              </span>
              <span className="text-sm text-subtext">{remaining} left</span>
            </>
          )}
        </div>

        {/* Latest reflections */}
        {latestTexts ? (
          latestTexts.map((text, i) => <ReflectionCard key={i} text={text} index={i} />)
        ) : (
          <p className="text-subtext text-sm text-center pt-8">
            Your reflections will appear here once generated
          </p>
        )}

        {genError && (
          <p className="text-error text-sm text-center mt-2 mb-1">{genError}</p>
        )}

        {/* Past */}
        {past.length > 0 && (
          <div className="mt-8">
            <p className="text-xs font-semibold text-subtext uppercase tracking-wider mb-3">
              Previous reflections
            </p>
            {past.map((r) => <PastReflectionGroup key={r.id} reflection={r} />)}
          </div>
        )}
      </div>

      {/* Bottom action */}
      <div
        className="fixed bottom-16 left-0 right-0 max-w-lg mx-auto px-5 pt-3 pb-5 bg-background border-t"
        style={{ borderColor: Colors.secondary + '60' }}
      >
        <button
          onClick={confirmGenerate}
          disabled={generating || atLimit}
          className="w-full flex items-center justify-center min-h-[52px] rounded-xl text-white text-base font-semibold transition-opacity disabled:opacity-70"
          style={{ backgroundColor: atLimit ? Colors.subtext + 'AA' : Colors.primary }}
        >
          {generating ? (
            <span className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
          ) : (
            atLimit ? 'Monthly limit reached' : latestTexts ? 'Regenerate' : 'Generate Reflections'
          )}
        </button>
      </div>

      {/* Confirm dialog */}
      {confirmOpen && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 px-6">
          <div className="bg-background rounded-2xl p-6 w-full max-w-sm">
            <h3 className="font-georgia text-primary text-lg mb-2">Regenerate reflections?</h3>
            <p className="text-sm text-ink leading-relaxed mb-6">
              This will create a new set of 3 reflections and use one of your monthly allowances.
              Your previous reflections will still be available in history.
            </p>
            <div className="flex gap-3">
              <button
                onClick={() => setConfirmOpen(false)}
                className="flex-1 min-h-[44px] rounded-xl border-[1.5px] border-secondary text-ink text-sm hover:bg-secondary/20 transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={() => { setConfirmOpen(false); handleGenerate(); }}
                className="flex-1 min-h-[44px] rounded-xl bg-primary text-white text-sm font-semibold hover:opacity-90 transition-opacity"
              >
                Regenerate
              </button>
            </div>
          </div>
        </div>
      )}
    </AppShell>
  );
}
